version: "3.3"

services:
  nats:
    image: nats:2
    ports:
      - 4222:4222
    networks:
      - internal

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - internal

  mongo:
    image: redis:alpine
    ports:
      - 27017:27017
    networks:
      - internal
    volumes:
      - mongo:/data/db


networks:
  internal:

volumes:
  data:
  mongo:
